import type { Gallery, GalleryImage, GenreSlug } from "@/types/gallery";

// AUTO-GENERATED by scripts/photos-build.mjs from curation/collections.txt — do not hand-edit.
// The EDIT (which frames, in which order, with what alt text) is a human decision recorded in
// that curation sheet; this file is only its published form. Sources are the photographer's own
// high-resolution library: auto-rotated, EXIF-stripped, resized and mozjpeg-optimised. Widths and
// heights are the TRUE output dimensions, so the exhibition hangs every frame uncropped.
// Regenerate: npm run photos:build

export const galleries: Gallery[] = [
  {
    slug: "familles",
    title: "Familles",
    intro: "Le quotidien et les liens, à la maison, en ville, au grand air.",
    cover: {
      src: "/galleries/familles/familles-a00.jpg",
      width: 1467, height: 2200, ratio: "aspect-[2/3]",
      alt: "Une famille dans les rues de Lyon, l'enfant porté dans les bras.",
    },
    images: [
      { src: "/galleries/familles/familles-a01.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Une famille réunie dans un champ, à la lumière chaude de l'automne." },
      { src: "/galleries/familles/familles-a02.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Un enfant au chapeau de paille, blotti contre son parent dans les herbes." },
      { src: "/galleries/familles/familles-a03.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Une mère et son fils marchent dans les hautes herbes, au soleil couchant." },
      { src: "/galleries/familles/familles-a04.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Une mère embrasse son bébé emmitouflé, tendresse d'une fin de journée." },
      { src: "/galleries/familles/familles-a05.jpg", width: 1575, height: 2200, ratio: "aspect-[2/3]", alt: "Un moment de jeu en famille, allongés ensemble, en noir et blanc." },
      { src: "/galleries/familles/familles-a06.jpg", width: 2200, height: 1523, ratio: "aspect-[3/2]", alt: "Parents et enfant réveillés ensemble, la douceur du matin à la maison." },
      { src: "/galleries/familles/familles-a07.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Une maman et son tout-petit dans une rue de Lyon, front contre front." },
      { src: "/galleries/familles/familles-a08.jpg", width: 1746, height: 2200, ratio: "aspect-[2/3]", alt: "Une maman embrasse son bébé, un instant volé sur un trottoir lyonnais." },
      { src: "/galleries/familles/familles-a09.jpg", width: 1661, height: 2200, ratio: "aspect-[2/3]", alt: "Un éclat de rire d'enfant, porté à bout de bras dans la ville." },
      { src: "/galleries/familles/familles-a10.jpg", width: 1490, height: 2200, ratio: "aspect-[2/3]", alt: "Une famille en promenade dans Lyon, complicité du quotidien." },
      { src: "/galleries/familles/familles-a11.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Un père, son bébé et le chien de la maison, un matin tranquille." },
      { src: "/galleries/familles/familles-a12.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Un bébé qui bâille sous son bonnet de fourrure, au creux des bras." },
    ],
  },
  {
    slug: "grossesse",
    title: "Grossesse",
    intro: "Les semaines douces avant l'arrivée du bébé.",
    cover: {
      src: "/galleries/grossesse/grossesse-a00.jpg",
      width: 1467, height: 2200, ratio: "aspect-[2/3]",
      alt: "Future maman devant les colonnes d'un palais lyonnais.",
    },
    images: [
      { src: "/galleries/grossesse/grossesse-a01.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Future maman adossée à une colonne de pierre, dans Lyon." },
      { src: "/galleries/grossesse/grossesse-a02.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Les futurs parents front contre front, sous une arche ancienne." },
      { src: "/galleries/grossesse/grossesse-a03.jpg", width: 1769, height: 2200, ratio: "aspect-[2/3]", alt: "Un couple qui se tient les mains, l'attente d'un enfant, en ville." },
      { src: "/galleries/grossesse/grossesse-a04.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Future maman de profil, la main sur le ventre, lumière douce." },
      { src: "/galleries/grossesse/grossesse-a05.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Les mains des futurs parents réunies sur le ventre arrondi." },
      { src: "/galleries/grossesse/grossesse-a06.jpg", width: 1523, height: 2200, ratio: "aspect-[2/3]", alt: "Un couple enlacé dans une cour lyonnaise, avant la naissance." },
      { src: "/galleries/grossesse/grossesse-a07.jpg", width: 1650, height: 2200, ratio: "aspect-[2/3]", alt: "Future maman rieuse, portée par son compagnon, dans la ville." },
      { src: "/galleries/grossesse/grossesse-a08.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "L'attente, à deux, sous les arcades d'un palais de Lyon." },
    ],
  },
  {
    slug: "couples",
    title: "Couples",
    intro: "Deux personnes, un lien. Sans poses figées.",
    cover: {
      src: "/galleries/couples/couples-a00.jpg",
      width: 1467, height: 2200, ratio: "aspect-[2/3]",
      alt: "Deux amoureux dans un jardin à la française, à la tombée du jour.",
    },
    images: [
      { src: "/galleries/couples/couples-a01.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Un couple marche côte à côte sur une grande pelouse, une demeure au loin." },
      { src: "/galleries/couples/couples-a02.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Deux amoureux enlacés près d'un bassin ancien, dans un parc." },
      { src: "/galleries/couples/couples-a03.jpg", width: 2200, height: 1389, ratio: "aspect-[3/2]", alt: "Un couple complice au bord de l'eau, lumière verte d'un jardin." },
      { src: "/galleries/couples/couples-a04.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Un regard partagé, tout près, dans la douceur d'un après-midi." },
      { src: "/galleries/couples/couples-a05.jpg", width: 2200, height: 1465, ratio: "aspect-[3/2]", alt: "Une femme respire un bouquet blanc, son compagnon à ses côtés." },
      { src: "/galleries/couples/couples-a06.jpg", width: 2200, height: 1641, ratio: "aspect-[3/2]", alt: "Deux amoureux rient ensemble, assis sur des marches de pierre." },
      { src: "/galleries/couples/couples-a07.jpg", width: 2200, height: 1479, ratio: "aspect-[3/2]", alt: "Un couple sur une terrasse dominant la vallée, au crépuscule." },
    ],
  },
  {
    slug: "portraits",
    title: "Portraits",
    intro: "Un portrait simple et sincère, à la lumière du jour.",
    cover: {
      src: "/galleries/portraits/portraits-a00.jpg",
      width: 1467, height: 2200, ratio: "aspect-[2/3]",
      alt: "Portrait d'une jeune femme en dentelle, lumière douce de fenêtre.",
    },
    images: [
      { src: "/galleries/portraits/portraits-a01.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Une mariée dans un champ de lavande, robe brodée, regard baissé." },
      { src: "/galleries/portraits/portraits-a02.jpg", width: 1479, height: 2200, ratio: "aspect-[2/3]", alt: "Portrait d'une mariée à la fenêtre, voile et dentelle, lumière douce." },
      { src: "/galleries/portraits/portraits-a03.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Un portrait en dentelle, en noir et blanc, à la fenêtre." },
      { src: "/galleries/portraits/portraits-a04.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Portrait franc d'une mariée, épaules dénudées, lumière de sous-bois." },
      { src: "/galleries/portraits/portraits-a05.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Une mariée devant une porte ancienne, bouquet à la main." },
      { src: "/galleries/portraits/portraits-a06.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Portrait de profil, un collier de perles, regard au loin." },
    ],
  },
  {
    slug: "mariages",
    title: "Mariages",
    intro: "Le récit d'une journée, de Lyon aux côtes de Bretagne. L'émotion plutôt que la mise en scène.",
    cover: {
      src: "/galleries/mariages/mariages-a00.jpg",
      width: 2200, height: 1467, ratio: "aspect-[3/2]",
      alt: "Les mariés face à la mer, elle en dentelle, lui en smoking blanc.",
    },
    images: [
      { src: "/galleries/mariages/mariages-a01.jpg", width: 1493, height: 2200, ratio: "aspect-[2/3]", alt: "Les préparatifs de la mariée, à la lumière d'une fenêtre." },
      { src: "/galleries/mariages/mariages-a02.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Les mariés s'embrassent dans une décapotable ancienne, jour de fête." },
      { src: "/galleries/mariages/mariages-a03.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Un baiser renversé, en noir et blanc, dans un parc." },
      { src: "/galleries/mariages/mariages-a04.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Les mariés enlacés dans un jardin, front contre front." },
      { src: "/galleries/mariages/mariages-a05.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "La mariée en robe à traîne fait tourner sa jupe sur la pelouse." },
      { src: "/galleries/mariages/mariages-a06.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Le marié soulève sa femme dans ses bras, éclat de rire." },
      { src: "/galleries/mariages/mariages-a07.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Les mariés marchent sur la plage, la robe portée par le vent." },
      { src: "/galleries/mariages/mariages-a08.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Un couple de mariés sur le sable, la mer en toile de fond." },
      { src: "/galleries/mariages/mariages-a09.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Le marié ouvre la portière d'un cabriolet blanc, en bord de mer." },
      { src: "/galleries/mariages/mariages-a10.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "La voiture des mariés devant un manoir de pierre, sous la pluie fine." },
      { src: "/galleries/mariages/mariages-a11.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Une demeure ancienne couverte de glycine, un jour de mariage." },
      { src: "/galleries/mariages/mariages-a12.jpg", width: 1450, height: 2048, ratio: "aspect-[2/3]", alt: "Portrait de la mariée en noir et blanc, un instant de calme." },
    ],
  },
];

/** Cross-genre pull (kept for the localisation type contract). */
export const featured: GalleryImage[] = [
  { src: "/galleries/mariages/mariages-a00.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Les mariés face à la mer, elle en dentelle, lui en smoking blanc." },
  { src: "/galleries/familles/familles-a07.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Une maman et son tout-petit dans une rue de Lyon, front contre front." },
  { src: "/galleries/grossesse/grossesse-a00.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Future maman devant les colonnes d'un palais lyonnais." },
  { src: "/galleries/couples/couples-a07.jpg", width: 2200, height: 1479, ratio: "aspect-[3/2]", alt: "Un couple sur une terrasse dominant la vallée, au crépuscule." },
  { src: "/galleries/portraits/portraits-a01.jpg", width: 1467, height: 2200, ratio: "aspect-[2/3]", alt: "Une mariée dans un champ de lavande, robe brodée, regard baissé." },
  { src: "/galleries/mariages/mariages-a07.jpg", width: 2200, height: 1467, ratio: "aspect-[3/2]", alt: "Les mariés marchent sur la plage, la robe portée par le vent." },
];

/** Ordered slugs for nav / static params. */
export const genreSlugs = galleries.map((g) => g.slug) as GenreSlug[];
