import type { GenreSlug } from "@/types/gallery";

// AUTO-GENERATED by scripts/photos-build.mjs from curation/collections.txt — do not hand-edit.
// The English overlay for the galleries. Generated from the SAME curation sheet as the French
// model, so the two locales can never drift out of sync (they did, twice, when maintained by
// hand). A missing EN string falls back to the French one at build time.
// Regenerate: npm run photos:build

export const galleryText: Record<
  GenreSlug,
  { title: string; intro: string; coverAlt: string; alts: string[] }
> = {
  familles: {
    title: "Families",
    intro: "Everyday life and the bonds within it, at home, in the city, out in the open.",
    coverAlt: "A family in the streets of Lyon, their child carried in their arms.",
    alts: [
      "A family gathered in a field, in the warm light of autumn.",
      "A child in a straw hat, nestled against their parent in the grass.",
      "A mother and her son walk through the tall grass at sunset.",
      "A mother kisses her bundled-up baby, the tenderness of late afternoon.",
      "A playful family moment, lying together, in black and white.",
      "Parents and child waking together, the softness of morning at home.",
      "A mother and her little one in a Lyon street, forehead to forehead.",
      "A mother kisses her baby, a stolen moment on a Lyon pavement.",
      "A child's burst of laughter, held up at arm's length in the city.",
      "A family on a walk through Lyon, the closeness of everyday life.",
      "A father, his baby and the family dog, one quiet morning.",
      "A baby yawning under a fur hood, cradled in someone's arms.",
    ],
  },
  grossesse: {
    title: "Maternity",
    intro: "The gentle weeks before the baby arrives.",
    coverAlt: "A mother-to-be before the columns of a Lyon palace.",
    alts: [
      "A mother-to-be leaning against a stone column, in Lyon.",
      "The parents-to-be forehead to forehead, beneath an old archway.",
      "A couple holding hands, awaiting their child, in the city.",
      "A mother-to-be in profile, hand on her belly, in soft light.",
      "The parents-to-be's hands joined on the rounded belly.",
      "A couple embracing in a Lyon courtyard, before the birth.",
      "A laughing mother-to-be, lifted by her partner, in the city.",
      "The wait, together, under the arcades of a Lyon palace.",
    ],
  },
  couples: {
    title: "Couples",
    intro: "Two people, one bond. No stiff poses.",
    coverAlt: "Two lovers in a formal French garden, at dusk.",
    alts: [
      "A couple walks side by side across a wide lawn, a mansion in the distance.",
      "Two lovers embracing beside an old pond, in a park.",
      "A close couple by the water, in the green light of a garden.",
      "A shared glance, up close, in the softness of an afternoon.",
      "A woman breathes in a white bouquet, her partner at her side.",
      "Two lovers laughing together, sitting on stone steps.",
      "A couple on a terrace overlooking the valley, at twilight.",
    ],
  },
  portraits: {
    title: "Portraits",
    intro: "A simple, sincere portrait, in daylight.",
    coverAlt: "Portrait of a young woman in lace, soft window light.",
    alts: [
      "A bride in a lavender field, embroidered dress, eyes lowered.",
      "A portrait of a bride by the window, veil and lace, soft light.",
      "A portrait in lace, in black and white, by the window.",
      "A candid portrait of a bride, bare shoulders, woodland light.",
      "A bride before an old doorway, bouquet in hand.",
      "A profile portrait, a string of pearls, gazing into the distance.",
    ],
  },
  mariages: {
    title: "Weddings",
    intro: "The story of a day, from Lyon to the Brittany coast. Emotion over staging.",
    coverAlt: "The newlyweds facing the sea, she in lace, he in a white tuxedo.",
    alts: [
      "The bride getting ready, in the light of a window.",
      "The newlyweds kiss in a vintage convertible, a day of celebration.",
      "A dipped kiss, in black and white, in a park.",
      "The newlyweds embracing in a garden, forehead to forehead.",
      "The bride in a trained gown spins her skirt on the lawn.",
      "The groom lifts his wife in his arms, a burst of laughter.",
      "The newlyweds walk on the beach, the dress carried by the wind.",
      "A newlywed couple on the sand, the sea as a backdrop.",
      "The groom opens the door of a white convertible, by the sea.",
      "The wedding car before a stone manor, in the fine rain.",
      "An old manor covered in wisteria, on a wedding day.",
      "Portrait of the bride in black and white, a moment of calm.",
    ],
  },
};

/** Cross-genre pull, aligned with `featured` in galleries.ts. */
export const featuredAlts: string[] = [
  "The newlyweds facing the sea, she in lace, he in a white tuxedo.",
  "A mother and her little one in a Lyon street, forehead to forehead.",
  "A mother-to-be before the columns of a Lyon palace.",
  "A couple on a terrace overlooking the valley, at twilight.",
  "A bride in a lavender field, embroidered dress, eyes lowered.",
  "The newlyweds walk on the beach, the dress carried by the wind.",
];
