// AUTO-GENERATED by scripts/sync-reviews.mjs (`npm run sync:reviews`) — the Google
// Business reviews, verbatim and newest first. Do not hand-edit: rerun the sync to
// refresh (git history records when each sync happened). Editorial policy — which
// reviews actually render — lives in src/content/testimonials.ts, so nothing is
// ever lost by curation. Workflow + credentials: docs/google-reviews.md.

import type { GoogleReview, GoogleRatingSummary } from "@/types/reviews";

/** Aggregate profile rating at the last sync, or null before the first sync. */
export const googleRating: GoogleRatingSummary | null = null;

/** All reviews returned by the last sync, newest first — real words only. */
export const googleReviews: GoogleReview[] = [];
