import type { Story } from "@/types/story";

// AUTO-GENERATED by scripts/stories-build.mjs — do not hand-edit.
// The EDIT (which photographs, in which order, with what alt text, and whether the story
// is public at all) is a human decision recorded in each story's story.txt; this file is
// only its published form. Sources are the photographer's own exports: auto-rotated,
// stripped of EXIF/ICC/XMP by the re-encode, resized and mozjpeg-optimised. Widths and
// heights are TRUE output dimensions, so the exhibition hangs every frame uncropped.
// Regenerate: npm run stories:build
//
// Empty because no story has been published yet: the photographer's manual selection is
// still to come. Drop a folder into the story library and run stories:build.

export const stories: Story[] = [];
