// Regenerates src/lib/image-blur.ts — the tiny blur-up placeholders next/image
// uses so a photograph resolves from a soft preview of itself rather than a flash
// (restores the workflow the map's header promises — B4).
//
// Run after adding or replacing any photograph under public/:
//
//   npm run gen:blur
//
// It scans public/ for JPEGs and emits one 12px-wide proportional JPEG data URI
// per file (the format of the existing map — small enough to inline, soft enough
// that next/image's blur filter reads as a preview, not pixels). The output file
// is fully regenerated and deterministic (keys sorted); never hand-edit it.

import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, "public");
const OUT_FILE = path.join(ROOT, "src", "lib", "image-blur.ts");

/** All JPEG files under `dir`, recursively. */
async function collectJpegs(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await collectJpegs(p)));
    else if (/\.jpe?g$/i.test(entry.name)) out.push(p);
  }
  return out;
}

const files = (await collectJpegs(PUBLIC_DIR)).sort();
if (files.length === 0) {
  console.error("gen-blur: no JPEGs found under public/ — nothing to do.");
  process.exit(1);
}

const entries = [];
for (const file of files) {
  const buf = await sharp(file).resize({ width: 12 }).jpeg({ quality: 70 }).toBuffer();
  const key = "/" + path.relative(PUBLIC_DIR, file).split(path.sep).join("/");
  entries.push(`  "${key}":\n    "data:image/jpeg;base64,${buf.toString("base64")}",`);
}

const banner = `// AUTO-GENERATED by scripts/gen-blur.mjs (\`npm run gen:blur\`) — tiny base64
// blur-up placeholders, keyed by the image's public path. Used by ImageFigure +
// hero + discover to render next/image \`placeholder="blur"\` so a photograph
// resolves from a soft preview of itself rather than a flash. Regenerate after
// adding/replacing images. Do not hand-edit.

export const blurMap: Record<string, string> = {
${entries.join("\n")}
};

/** blurDataURL for a public image path, or undefined if none was generated. */
export function blurFor(src?: string): string | undefined {
  return src ? blurMap[src] : undefined;
}
`;

await writeFile(OUT_FILE, banner);
console.log(`gen-blur: wrote ${files.length} placeholders → ${path.relative(ROOT, OUT_FILE)}`);
